apiVersion: v1
kind: Service
metadata:
  name: bdatgeo-rest-api-go
  namespace: bigdata-at-geo
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: api-port
  selector:
    app: bdatgeo-rest-api-go